### ISSUE TITLE
Frage zur Interpretation der gegebenen Datenfelder (negative Werte)

### ISSUE THREAD

**Issue by atticus-sullivan** [ard-data/2020-rki-archive#2]
Hallo,

mir ist aufgefallen, dass in den Feldern (v.A. Neu*) ab und zu auch negative Werte vorkommen. Ein Blick in die Doc auf [https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0) zeigt, dass es hierbei darum geht, in welchen Publikationen die jeweiligen Fälle jeweils vorkommen.

Leider verstehe ich nicht so ganz was genau damit gemeint ist. Bedeutet eine `-1` als `NeuerFall`, dass die Fälle in der Publikation des letzten Tages "zu viel" berichtet wurde? (so lese ich `Fall ist nur in der Publikation des Vortags enthalten`)

Auch die in der Doc gegebene Berechnungsvorschrift für die gesamten Fälle und die Fälle im Vergleich zum Vortag klärt das für mich leider nicht ganz auf.

Vielleicht kann jemand an dieser Stelle nochmal etwas genauer auf diese Attribut(e) eingehen? (Ohne dieses Wissen ist eine Verarbeitung der Daten abseits der gegebenen Anfragen soweit ich die Daten bisher verstehe leider nur schwer möglich)

**Comment by MichaelKreil** [comment]
Aus verschiedenen Gründen kann eine gemeldete Infektion sich nachträglich verändern, z.B. könnte sich theoretisch durch die Nachverfolgung ergeben, dass eine als infiziert gemeldete Person in Wirklichkeit ein anderes Alter hat, zu einem anderen Landkreis gehört, ein positiver Test sich nachträglich als falsch herausstellt, uvm.
Das RKI hat sich dazu entschlossen, in seiner Datenstruktur nicht nur den aktuell bekannten Infektionsstand zu veröffentlichen, sondern auch eine Art "Diff" zum Vortag zu integrieren.
Die negativen Zahlen für "NeuerFall", "NeuerTodesfall" und "NeuGenesen" sollen anzeigen, dass hier eine Veränderung zum Vortag revidiert wurde.

Ich persönlich halte diese Art der Kodierung durch das RKI für unnötig aufwändig und unnötig verwirrend.
Meine persönliche Empfehlung: Alle Einträge mit Werten < 0 einfach rausfiltern/ignorieren.
